### ISSUE TITLE
This mod will crash when used together with the 'atlas_combat' mod

### ISSUE THREAD

**Issue by Diemoerm** [Tavi007/ElementalCombat#68]
version：1.18.2

Init ItemPhysic coremods ...
Exception in thread "main" java.lang.module.ResolutionException: Modules MixinExtras.beta._5 and atlascombat export package com.llamalad7.mixinextras to module sliceanddice
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

**Comment by Tavi007** [comment]
I can take a look at it. However i don't see any of my mods classes mentioned in the stacktrace, so i'm not sure, where to start.
I have a newer version in the pipeline with generel stability improvements. Maybe this will fix the issue already.

I will check if the issue persist, but would also like to hear confirmation from you, if possible :)

**Comment by Diemoerm** [comment]
The text above is the part marked in red font that I found in lastest.log.
After testing, My game can start normally without installing both 'Elemental Combat' and 'atlas_combat' at the same time.

**Comment by Tavi007** [comment]
I uploaded a new version. Could please confirm, if the issue still exist on your end?

**Comment by Tavi007** [comment]
Closing the issue, because no further feedback was given.
