### ISSUE TITLE
[crash]1.16.5 with Hwyla

### ISSUE THREAD

**Issue by 2929762171** [Tavi007/ElementalCombat#70]
minecraft 1.16.5
forge 36.2.39
Hwyla-forge-1.10.11-B78_1.16.2
======================

[Worker-ResourceReload-1/ERROR]: Exception caught during firing event: mcp.mobius.waila.api.IRegistrar.addComponent(Lmcp/mobius/waila/api/IEntityComponentProvider;Lmcp/mobius/waila/api/TooltipPosition;Ljava/lang/Class;)V
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2634/1996111320@f1bd0c7
java.lang.NoSuchMethodError: mcp.mobius.waila.api.IRegistrar.addComponent(Lmcp/mobius/waila/api/IEntityComponentProvider;Lmcp/mobius/waila/api/TooltipPosition;Ljava/lang/Class;)V
	at Tavi007.ElementalCombat.interaction.CombatPropertiesWailaPlugin.register(CombatPropertiesWailaPlugin.java:18)
	at mcp.mobius.waila.Waila.lambda$null$3(Waila.java:86)
	at java.lang.Iterable.forEach(Unknown Source)
	at mcp.mobius.waila.Waila.lambda$loadComplete$4(Waila.java:78)
	at java.util.ArrayList.forEach(Unknown Source)
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:77)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

[11:57:32] [Worker-ResourceReload-1/ERROR]: Caught exception during event FMLLoadCompleteEvent dispatch for modid waila
java.lang.NoSuchMethodError: mcp.mobius.waila.api.IRegistrar.addComponent(Lmcp/mobius/waila/api/IEntityComponentProvider;Lmcp/mobius/waila/api/TooltipPosition;Ljava/lang/Class;)V
	at Tavi007.ElementalCombat.interaction.CombatPropertiesWailaPlugin.register(CombatPropertiesWailaPlugin.java:18) ~[elementalcombat:1.16.5-1.2.0.4]
	at mcp.mobius.waila.Waila.lambda$null$3(Waila.java:86) ~[waila:1.10.11-B78_1.16.2]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_333]
	at mcp.mobius.waila.Waila.lambda$loadComplete$4(Waila.java:78) ~[waila:1.10.11-B78_1.16.2]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_333]
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:77) ~[waila:1.10.11-B78_1.16.2]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[forge:36.2]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_333]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_333]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_333]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_333]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_333]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_333]

**Comment by Tavi007** [comment]
Hey. Thanks for the crash report. Could you please also provide the waila/wthit version that you used? I myself used the following version when I wrote the 1.16 version of the mod: 
version_waila=1.10.11-B78_1.16.2
version_wthit=2.10.14

**Comment by 2929762171** [comment]
I didn't know wthit before, crash only with the waila.
Now I"m using wthit, It works normally.
Thank you !
